"""Rename metadata column to meta_data

Revision ID: 63df7de0f80a
Revises: c24a0c5b5c36
Create Date: 2025-10-19 23:39:25.717059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63df7de0f80a'
down_revision: Union[str, Sequence[str], None] = 'c24a0c5b5c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
